"""Generate optimized project image variants for the portfolio.

Recommended Windows workflow:
  tools\\launch.bat

Run directly from any working directory:
  python tools/generate-image-variants.py [--force]

The editable project data should keep pointing at original media files. This
script creates missing images under each media/optimized folder and writes
image-variants.js so the site can automatically load the right-sized file.
Pass --force after replacing an existing original or to regenerate everything.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from PIL import Image, ImageOps


ROOT = Path(__file__).resolve().parents[1]
MEDIA_ROOT = ROOT / "projects"
MANIFEST_PATH = ROOT / "image-variants.js"
IMAGE_SUFFIXES = {".jpg", ".jpeg", ".png"}
VARIANTS = {
    "small": {"max_edge": 520, "quality": 72},
    "medium": {"max_edge": 900, "quality": 76},
    "large": {"max_edge": 1500, "quality": 82},
}


def repo_path(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def variant_path(source: Path, label: str) -> Path:
    return source.parent / "optimized" / f"{source.stem}-{label}.jpg"


def resize_image(image: Image.Image, max_edge: int) -> Image.Image:
    resized = image.copy()
    resized.thumbnail((max_edge, max_edge), Image.Resampling.LANCZOS)
    return resized


def prepare_rgb(image: Image.Image) -> Image.Image:
    image = ImageOps.exif_transpose(image)
    if image.mode in {"RGBA", "LA"}:
        background = Image.new("RGB", image.size, "white")
        background.paste(image, mask=image.getchannel("A"))
        return background
    return image.convert("RGB")


def save_variant(source_image: Image.Image, source: Path, label: str, config: dict) -> dict:
    output = variant_path(source, label)
    output.parent.mkdir(exist_ok=True)

    resized = resize_image(source_image, config["max_edge"])
    resized.save(
        output,
        format="JPEG",
        quality=config["quality"],
        optimize=True,
        progressive=True,
    )

    return {
        "src": repo_path(output),
        "width": resized.width,
        "height": resized.height,
        "bytes": output.stat().st_size,
    }


def find_sources() -> list[Path]:
    sources = []
    for media_dir in MEDIA_ROOT.rglob("media"):
        if not media_dir.is_dir():
            continue

        sources.extend(
            path
            for path in media_dir.iterdir()
            if path.is_file() and path.suffix.lower() in IMAGE_SUFFIXES
        )

    return sorted(sources)


def variant_exists(source: Path, label: str) -> bool:
    return variant_path(source, label).is_file()


def existing_variant(source: Path, label: str) -> dict:
    output = variant_path(source, label)
    with Image.open(output) as image:
        width, height = image.size

    return {
        "src": repo_path(output),
        "width": width,
        "height": height,
        "bytes": output.stat().st_size,
    }


def generate(force: bool = False) -> tuple[dict, int, int]:
    manifest = {}
    generated_count = 0
    skipped_count = 0
    sources = find_sources()

    for source in sources:
        with Image.open(source) as raw_image:
            image = prepare_rgb(raw_image)

        entry = {
            "original": {
                "src": repo_path(source),
                "width": image.width,
                "height": image.height,
                "bytes": source.stat().st_size,
            },
            "variants": {},
        }

        for label, config in VARIANTS.items():
            if force or not variant_exists(source, label):
                entry["variants"][label] = save_variant(image, source, label, config)
                generated_count += 1
            else:
                entry["variants"][label] = existing_variant(source, label)
                skipped_count += 1

        manifest[repo_path(source)] = entry

    return manifest, generated_count, skipped_count


def write_manifest(manifest: dict) -> None:
    manifest_json = json.dumps(manifest, indent=2, sort_keys=True)
    MANIFEST_PATH.write_text(
        "// Generated by tools/generate-image-variants.py.\n"
        "// Keep editing project data with original media paths; this manifest\n"
        "// lets the site choose smaller generated images at runtime.\n"
        f"window.portfolioImageVariants = {manifest_json};\n",
        encoding="utf-8",
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate responsive image variants for project media."
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Regenerate every variant even when an up-to-date file exists.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    manifest, generated_count, skipped_count = generate(force=args.force)
    write_manifest(manifest)

    original_bytes = sum(item["original"]["bytes"] for item in manifest.values())
    variant_bytes = sum(
        variant["bytes"]
        for item in manifest.values()
        for variant in item["variants"].values()
    )
    print(f"images={len(manifest)}")
    print(f"variants_generated={generated_count}")
    print(f"variants_current={skipped_count}")
    print(f"original_mb={original_bytes / 1024 / 1024:.2f}")
    print(f"variants_mb={variant_bytes / 1024 / 1024:.2f}")
    print(f"manifest={repo_path(MANIFEST_PATH)}")


if __name__ == "__main__":
    main()
