"""Generate optimized project image variants for the portfolio.

Run from the repository root:
  python tools/generate-image-variants.py

The editable project data should keep pointing at original media files. This
script creates smaller images under each media/optimized folder and writes
image-variants.js so the site can automatically load the right-sized file.
"""

from __future__ import annotations

import json
from pathlib import Path

from PIL import Image, ImageOps


ROOT = Path(__file__).resolve().parents[1]
MEDIA_ROOT = ROOT / "projects"
MANIFEST_PATH = ROOT / "image-variants.js"
IMAGE_SUFFIXES = {".jpg", ".jpeg", ".png"}
VARIANTS = {
    "small": {"max_edge": 520, "quality": 72},
    "medium": {"max_edge": 900, "quality": 76},
    "large": {"max_edge": 1500, "quality": 82},
}


def repo_path(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def variant_path(source: Path, label: str) -> Path:
    return source.parent / "optimized" / f"{source.stem}-{label}.jpg"


def resize_image(image: Image.Image, max_edge: int) -> Image.Image:
    resized = image.copy()
    resized.thumbnail((max_edge, max_edge), Image.Resampling.LANCZOS)
    return resized


def prepare_rgb(image: Image.Image) -> Image.Image:
    image = ImageOps.exif_transpose(image)
    if image.mode in {"RGBA", "LA"}:
        background = Image.new("RGB", image.size, "white")
        background.paste(image, mask=image.getchannel("A"))
        return background
    return image.convert("RGB")


def save_variant(source_image: Image.Image, source: Path, label: str, config: dict) -> dict:
    output = variant_path(source, label)
    output.parent.mkdir(exist_ok=True)

    resized = resize_image(source_image, config["max_edge"])
    resized.save(
        output,
        format="JPEG",
        quality=config["quality"],
        optimize=True,
        progressive=True,
    )

    return {
        "src": repo_path(output),
        "width": resized.width,
        "height": resized.height,
        "bytes": output.stat().st_size,
    }


def clear_old_variants() -> None:
    for optimized_dir in MEDIA_ROOT.glob("*/media/optimized"):
        if not optimized_dir.is_dir():
            continue

        for path in optimized_dir.iterdir():
            if path.is_file() and path.suffix.lower() in IMAGE_SUFFIXES:
                path.unlink()


def generate() -> dict:
    manifest = {}
    sources = sorted(
        path
        for path in MEDIA_ROOT.glob("*/media/*")
        if path.is_file()
        and path.suffix.lower() in IMAGE_SUFFIXES
        and "optimized" not in path.parts
    )

    for source in sources:
        with Image.open(source) as raw_image:
            image = prepare_rgb(raw_image)

        entry = {
            "original": {
                "src": repo_path(source),
                "width": image.width,
                "height": image.height,
                "bytes": source.stat().st_size,
            },
            "variants": {},
        }

        for label, config in VARIANTS.items():
            entry["variants"][label] = save_variant(image, source, label, config)

        manifest[repo_path(source)] = entry

    return manifest


def write_manifest(manifest: dict) -> None:
    manifest_json = json.dumps(manifest, indent=2, sort_keys=True)
    MANIFEST_PATH.write_text(
        "// Generated by tools/generate-image-variants.py.\n"
        "// Keep editing project data with original media paths; this manifest\n"
        "// lets the site choose smaller generated images at runtime.\n"
        f"window.portfolioImageVariants = {manifest_json};\n",
        encoding="utf-8",
    )


def main() -> None:
    clear_old_variants()
    manifest = generate()
    write_manifest(manifest)

    original_bytes = sum(item["original"]["bytes"] for item in manifest.values())
    variant_bytes = sum(
        variant["bytes"]
        for item in manifest.values()
        for variant in item["variants"].values()
    )
    print(f"images={len(manifest)}")
    print(f"original_mb={original_bytes / 1024 / 1024:.2f}")
    print(f"variants_mb={variant_bytes / 1024 / 1024:.2f}")
    print(f"manifest={repo_path(MANIFEST_PATH)}")


if __name__ == "__main__":
    main()
